import { User } from 'src/app/flats/interfaces';

// Generated by https://quicktype.io
export interface UserComplete extends User {
  image: Image;
  name: string;
}

export interface Image {
  public_id: string;
  secure_url: string;
}
